Testing | Packaging v2
YunoHost-Apps/pyload_ynh pull request #11
Opened 2023-12-05 00:40 UTC by alexAubin

2023-12-05 00:40 UTC, alexAubin commented
!testme

2023-12-13 12:41 UTC, Salamandar requested changes

2023-12-13 12:41 UTC, Salamandar commented on scripts/change_url
> -nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf
Line 19, `--line_match="Proxy listening"` should be remove because action=stop

2023-12-13 12:41 UTC, Salamandar commented on scripts/upgrade
> -#=================================================
Here, ynh_systemd_action start fails because it’s already started. You should stop it at the beginning of the upgrade.

2023-12-13 12:47 UTC, Salamandar commented
!testme

2023-12-13 13:07 UTC, Salamandar commented
@alexAubin fixed now !

2023-12-13 13:21 UTC, alexAubin commented
Cheers :O

2023-12-13 13:21 UTC, merged